blog/urls.py
from django.conf.urls import url

from .views import (
    ArticleListView,
    ArticleDetailView
)


app_name = 'articles'
urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name = 'article-list'),
    url(r'^<int:pk>$', ArticleDetailView.as_view(), name = 'article-detail'),

]

menus/urls.py
 
from django.conf.urls import url

from .views import (
    ItemListView, 
    ItemDetailView, 
    ItemCreateView, 
    ItemUpdateView
    )

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name = 'create'),
    url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(), name = 'detail'), 
    url(r'^$', ItemListView.as_view(), name = 'list'),

]

muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from restaurants.views import TemplateView
from django.contrib.auth.views import LoginView

from restaurants.views import (
    restaurant_createview,
    restaurant_listview,
    RestaurantListView, 
    RestaurantDetailView,
    RestaurantCreateView, )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^login/$', LoginView.as_view(), name = 'login'),
    url(r'^items/', include(('menus.urls', 'menus'),namespace = 'menus')),
    url(r'^restaurants/', include(('restaurants.urls','restaurants'), namespace = 'restaurants')),
    url(r'^/', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'),name='contact')
    # url(r'^restaurants/$', restaurant_listview),
    # url(r'^restaurants/nonveg$', NonVegRestaurantListView.as_view()),
    # url(r'^restaurants/(?P<pk>\w+)/$', RestaurantListView.as_view()), 
    # url(r'^restaurants/veg$', VegRestaurantListView.as_view()),
]

templates/snippets/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

templates/snippets/js.html
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

templates/snippets/nav.html
<div class="container">
    <h1>Muypicky</h1>
    <div class="container">
    <a href='{% url "home" %}'>Home | </a>
    <a href='{% url "about" %}'>About | </a>
    <a href='{% url "contact" %}'>Contact | </a>
    <a href='{% url "restaurants:list" %}'>Restaurants | </a>
   
</div>
</div>

templates/snippets/sidebar.html
<ul>
    <li>item1</li>
    <li>item2</li>
    <li>item3</li>
</ul>